replicaCount: 1

image:
  repository: jaimehenao8126/monitor-argocd-opcion1
  tag: v3
  pullPolicy: IfNotPresent

cronSchedule: "*/5 * * * *" # Ejecutar cada 5 minutos

serviceAccount:
  create: true
  name: ""

resources: {}