replicaCount: 1

image:
  repository: jaimehenao8126/monitor-argocd-opcion1
  tag: 97d991d83c5c7587442177a7cd591e06b4775ff1
  pullPolicy: IfNotPresent

cronSchedule: "*/1 * * * *" # Ejecutar cada 5 minutos

serviceAccount:
  create: true
  name: ""

resources: {}

env:
  ARGOCD_SERVER: "argocd-server.argocd.svc.cluster.local:443"
  ARGOCD_USERNAME: "admin"
  ARGOCD_PASSWORD: "Thomas#1109"