replicaCount: 1

image:
  repository: jaimehenao8126/monitor-argocd-opcion1
  tag: fd920b08e6cdd96c6ec8d10c8513da9c9f17a712
  pullPolicy: IfNotPresent

cronSchedule: "*/1 * * * *" # Ejecutar cada 5 minutos

serviceAccount:
  create: true
  name: ""

resources: {}

env:
  ARGOCD_SERVER: "argocd-server.argocd.svc.cluster.local:443"
  ARGOCD_USERNAME: "admin"
  ARGOCD_PASSWORD: "Thomas#1109"

syncPolicy:
  automated:
    prune: true
    selfHeal: true

source:
  repoURL: https://github.com/JaimeHenaoChallange/monitor-argocd-opcion1.git
  targetRevision: main
  path: script-py/monitor-argocd-opcion1