replicaCount: 1

image:
  repository: jaimehenao8126/monitor-argocd-opcion1
  tag: 4377b4796582073b74a1ceaea89f95dd9a6942b6
  pullPolicy: IfNotPresent

cronSchedule: "*/5 * * * *" # Ejecutar cada 5 minutos

serviceAccount:
  create: true
  name: ""

resources: {}