replicaCount: 1

image:
  repository: jaimehenao8126/monitor-argocd-opcion1
  tag: 46fad808134a11d6820a6186d732319dd8db1893
  pullPolicy: IfNotPresent

cronSchedule: "*/5 * * * *" # Ejecutar cada 5 minutos

serviceAccount:
  create: true
  name: ""

resources: {}