replicaCount: 1

image:
  repository: jaimehenao8126/monitor-argocd-opcion1
  tag: 3f6a6870209a987e338dee6b6aa158828fe0cd40
  pullPolicy: IfNotPresent

cronSchedule: "*/1 * * * *" # Ejecutar cada 5 minutos

serviceAccount:
  create: true
  name: ""

resources: {}

env:
  ARGOCD_SERVER: "argocd-server.argocd.svc.cluster.local:443"
  ARGOCD_USERNAME: "admin"
  ARGOCD_PASSWORD: "Thomas#1109"