replicaCount: 1

image:
  repository: jaimehenao8126/monitor-argocd-opcion1
  tag: 74e51be9b183799d7c2c4625308bd5546b741262
  pullPolicy: IfNotPresent

cronSchedule: "*/5 * * * *" # Ejecutar cada 5 minutos

serviceAccount:
  create: true
  name: ""

resources: {}