apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: "{{ .Values.cronSchedule }}" # Cronograma definido en values.yaml
  successfulJobsHistoryLimit: 3 # Mantener solo los últimos 3 pods exitosos
  failedJobsHistoryLimit: 1     # Mantener solo el último pod fallido
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .Chart.Name }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: ARGOCD_SERVER
              value: "{{ .Values.env.ARGOCD_SERVER }}"
            - name: ARGOCD_USERNAME
              value: "{{ .Values.env.ARGOCD_USERNAME }}"
            - name: ARGOCD_PASSWORD
              value: "{{ .Values.env.ARGOCD_PASSWORD }}"
          restartPolicy: Never