apiVersion: batch/v1
kind: CronJob
metadata:
  name: monitor-argocd
  namespace: default
spec:
  schedule: "*/5 * * * *" # Ejecutar cada 5 minutos
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: monitor-argocd
            image: jaimehenao8126/monitor-argocd-opcion1:latest
            imagePullPolicy: Always
            env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: monitor-argocd-env
                  key: SLACK_WEBHOOK_URL
            - name: ARGOCD_SERVER
              value: "argocd-server.argocd.svc.cluster.local:443"
            - name: ARGOCD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: monitor-argocd-env
                  key: ARGOCD_USERNAME
            - name: ARGOCD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: monitor-argocd-env
                  key: ARGOCD_PASSWORD
          restartPolicy: Never