name: CD

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME_JAIME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD_JAIME }}
  IMAGE_NAME: monitor-argocd-opcion1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -f ./Docker/Dockerfile ./Docker

      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update values.yaml and commit
        run: |
          sed -i 's|tag:.*|tag: '${{ github.sha }}'|' ./values.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ./values.yaml
          git commit -m "Update values.yaml with new image tag" || echo "No changes to commit"
          git push