name: CD

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME_JAIME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD_JAIME }}
  IMAGE_NAME: monitor-argocd-opcion1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print current directory
        run: pwd

      - name: List all files
        run: ls -R

      - name: List Docker folder
        run: ls -R ./script-py/monitor-argocd-opcion1/Docker

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -f ./monitor-argocd-opcion1/Docker/Dockerfile ./script-py/monitor-argocd-opcion1

      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update image in ArgoCD application
        run: |
          sed -i 's|image:.*|image: '${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'|' ./monitor-argocd-opcion1/values.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ./script-py/monitor-argocd-opcion1/values.yaml
          git commit -m "Update image in values.yaml to ${{ github.sha }}" || echo "No changes to commit"
          git push

      - name: Sync ArgoCD Application
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
          argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
          argocd app sync monitor-argocd-opcion1 